### ISSUE TITLE
How do I do this to run on Windows?

### ISSUE THREAD

**Issue by ghost** [jminor/sql-gui#2]

**Comment by jminor** [comment]
I haven't tried it on Windows, only Mac and Linux. It shouldn't be too hard to get it to compile and run on WIndows, since there's nothing platform specific in the code. There's some clues in the GitHub actions config here if you want to give it a try: https://github.com/jminor/sql-gui/blob/main/.github/workflows/build.yaml

Also, I made a couple of other ImGui apps that do compile and run on Windows. Those use cmake to build. You can see details here: https://github.com/jminor/nightingale/blob/main/.github/workflows/build.yaml and here: https://github.com/OpenTimelineIO/raven/blob/main/.github/workflows/build.yaml
